// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWnzWFI13fwD3uQoAAiUvq9-_zDn1Nso',
    appId: '1:988252571774:web:4abe0937e2ee9f39eef02f',
    messagingSenderId: '988252571774',
    projectId: 'blog-app-9a272',
    authDomain: 'blog-app-9a272.firebaseapp.com',
    storageBucket: 'blog-app-9a272.firebasestorage.app',
    measurementId: 'G-38TDZRX79K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nb6cCv658fRmvjgUa2EtVBiPuoVRal4',
    appId: '1:988252571774:android:f022791439b8c18eeef02f',
    messagingSenderId: '988252571774',
    projectId: 'blog-app-9a272',
    storageBucket: 'blog-app-9a272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgTaiCFjUSV2T7EizwUad_tL5yLjzE6E',
    appId: '1:988252571774:ios:84bd39bef45770eeeef02f',
    messagingSenderId: '988252571774',
    projectId: 'blog-app-9a272',
    storageBucket: 'blog-app-9a272.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBgTaiCFjUSV2T7EizwUad_tL5yLjzE6E',
    appId: '1:988252571774:ios:84bd39bef45770eeeef02f',
    messagingSenderId: '988252571774',
    projectId: 'blog-app-9a272',
    storageBucket: 'blog-app-9a272.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgWnzWFI13fwD3uQoAAiUvq9-_zDn1Nso',
    appId: '1:988252571774:web:ac634390b8c9b730eef02f',
    messagingSenderId: '988252571774',
    projectId: 'blog-app-9a272',
    authDomain: 'blog-app-9a272.firebaseapp.com',
    storageBucket: 'blog-app-9a272.firebasestorage.app',
    measurementId: 'G-YLXR93E47Q',
  );
}
